#!/usr/bin/env python3
"""
CIM Array Evaluation Script
Generates array netlist, runs ngspice simulation, compares MVM results against numpy.
"""

import subprocess
import tempfile
import os
import csv
import json
import re
import sys
import numpy as np
from pathlib import Path

BLOCK_DIR = Path(__file__).parent.resolve()
BITCELL_CIR = BLOCK_DIR / ".." / "bitcell" / "design.cir"
PWM_CIR = BLOCK_DIR / ".." / "pwm-driver" / "design.cir"
SPECS_FILE = BLOCK_DIR / "specs.json"
PARAMS_FILE = BLOCK_DIR / "parameters.csv"
SKY130_LIB = "sky130_models/sky130.lib.spice"

VDD = 1.8
N_TEST_VECTORS = 10
INPUT_BITS = 4  # 4-bit PWM encoding -> values 0..15


# ---------------------------------------------------------------------------
# Upstream parameter loading
# ---------------------------------------------------------------------------

def load_bitcell_params():
    """Load measured bitcell parameters from upstream block."""
    meas_file = BLOCK_DIR / ".." / "bitcell" / "measurements.json"
    defaults = {
        "i_read_ua": 10.0,
        "i_leak_na": 10.0,
        "c_bl_cell_ff": 0.5,
        "t_read_ns": 2.0,
    }
    if meas_file.exists():
        with open(meas_file) as f:
            data = json.load(f)
        for k in defaults:
            if k in data:
                defaults[k] = float(data[k])
    else:
        print(f"WARNING: {meas_file} not found, using defaults")
    return defaults


def load_pwm_params():
    """Load measured PWM driver parameters from upstream block."""
    meas_file = BLOCK_DIR / ".." / "pwm-driver" / "measurements.json"
    defaults = {
        "t_lsb_ns": 2.0,
        "t_rf_ns": 0.2,
    }
    if meas_file.exists():
        with open(meas_file) as f:
            data = json.load(f)
        for k in defaults:
            if k in data:
                defaults[k] = float(data[k])
    else:
        print(f"WARNING: {meas_file} not found, using defaults")
    return defaults


# ---------------------------------------------------------------------------
# Load parameters
# ---------------------------------------------------------------------------

def load_parameters(override=None):
    """Load array parameters from parameters.csv with optional overrides."""
    params = {}
    with open(PARAMS_FILE) as f:
        reader = csv.DictReader(f)
        for row in reader:
            name = row["name"]
            params[name] = (float(row["min"]) + float(row["max"])) / 2  # default: midpoint
    if override:
        params.update(override)
    return params


def load_specs():
    with open(SPECS_FILE) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Bitcell subcircuit extraction
# ---------------------------------------------------------------------------

def get_bitcell_subckt():
    """Extract the cim_bitcell subcircuit from the bitcell design file."""
    if BITCELL_CIR.exists():
        text = BITCELL_CIR.read_text()
        # Extract .subckt cim_bitcell ... .ends cim_bitcell
        match = re.search(
            r"(\.subckt\s+cim_bitcell\b.*?\.ends\s+cim_bitcell)",
            text, re.DOTALL | re.IGNORECASE
        )
        if match:
            return match.group(1)
    # Fallback: use the placeholder from design.cir
    print("WARNING: Using placeholder bitcell subcircuit")
    return None  # Will use the one already in design.cir


# ---------------------------------------------------------------------------
# Netlist generation
# ---------------------------------------------------------------------------

def generate_netlist(n_rows, n_cols, weight_matrix, input_vector, params,
                     bitcell_params, pwm_params, corner="tt"):
    """
    Generate a SPICE netlist for an n_rows x n_cols CIM array.

    weight_matrix: np.array of shape (n_rows, n_cols) with values 0 or 1
    input_vector:  np.array of shape (n_rows,) with values 0..15 (4-bit)
    params:        dict with Wpre, Lpre, Tpre_ns, Cbl_extra_ff
    """
    Wpre = params["Wpre"]
    Lpre = params["Lpre"]
    Tpre_ns = params["Tpre_ns"]
    Cbl_extra_ff = params["Cbl_extra_ff"]
    t_lsb = pwm_params["t_lsb_ns"]
    t_rf = pwm_params["t_rf_ns"]
    c_bl_cell = bitcell_params["c_bl_cell_ff"]

    # Total bitline capacitance
    c_bl_total_ff = n_rows * c_bl_cell + Cbl_extra_ff

    # Timing
    t_start_ns = Tpre_ns + 1.0  # compute starts after precharge + margin
    t_max_pulse_ns = 15 * t_lsb  # maximum pulse width (input=15)
    t_end_ns = t_start_ns + t_max_pulse_ns + 20  # settle margin
    t_sim_ns = t_end_ns + 10

    lines = []
    lines.append(f"* CIM Array {n_rows}x{n_cols} -- Auto-generated by evaluate.py")
    lines.append(f".lib \"{SKY130_LIB}\" {corner}")
    lines.append(f".param supply={VDD}")
    lines.append("")

    # Bitcell subcircuit
    bitcell_subckt = get_bitcell_subckt()
    if bitcell_subckt:
        lines.append("* Bitcell subcircuit (from upstream)")
        lines.append(bitcell_subckt)
    else:
        # Use placeholder
        lines.append("* Bitcell subcircuit (placeholder)")
        lines.append(".subckt cim_bitcell bl blb wl wwl q qb vdd vss")
        lines.append(f"XPL vdd q  qb vdd sky130_fd_pr__pfet_01v8 w=0.84 l=0.15")
        lines.append(f"XPR vdd qb q  vdd sky130_fd_pr__pfet_01v8 w=0.84 l=0.15")
        lines.append(f"XNL vss q  qb vss sky130_fd_pr__nfet_01v8 w=0.42 l=0.15")
        lines.append(f"XNR vss qb q  vss sky130_fd_pr__nfet_01v8 w=0.42 l=0.15")
        lines.append(f"XAXL q   wwl blb  vss sky130_fd_pr__nfet_01v8 w=0.42 l=0.15")
        lines.append(f"XAXR qb  wwl bl   vss sky130_fd_pr__nfet_01v8 w=0.42 l=0.15")
        lines.append(f"XRD1 bl  q   mid  vss sky130_fd_pr__nfet_01v8 w=1.0 l=0.15")
        lines.append(f"XRD2 mid wl  vss  vss sky130_fd_pr__nfet_01v8 w=1.0 l=0.15")
        lines.append(".ends cim_bitcell")
    lines.append("")

    # Precharge subcircuit
    lines.append("* Precharge circuit")
    lines.append(".subckt precharge bl pre vdd vss")
    lines.append(f"XPRE vdd pre bl vdd sky130_fd_pr__pfet_01v8 w={Wpre} l={Lpre}")
    lines.append(".ends precharge")
    lines.append("")

    # Supply
    lines.append("Vdd vdd 0 {supply}")
    lines.append("Vss vss 0 0")
    lines.append("")

    # Precharge signal
    lines.append(f"* Precharge: high for {Tpre_ns}ns then low")
    lines.append(f"Vpre pre 0 PWL(0 1.8 {Tpre_ns}n 1.8 {Tpre_ns + 0.1}n 0)")
    lines.append("")

    # Precharge transistors and parasitic caps for each column
    for c in range(n_cols):
        lines.append(f"Xpre{c} bl{c} pre vdd vss precharge")
    lines.append("")
    for c in range(n_cols):
        lines.append(f"Cbl{c} bl{c} 0 {c_bl_total_ff}f")
    lines.append("")

    # Wordline signals (PWL sources encoding input vector)
    lines.append("* Wordline signals (PWM-encoded inputs)")
    for r in range(n_rows):
        val = int(input_vector[r])
        if val == 0:
            lines.append(f"Vwl{r} wl{r} 0 0")
        else:
            pw_ns = val * t_lsb
            t0 = t_start_ns
            lines.append(
                f"Vwl{r} wl{r} 0 PWL(0 0 {t0}n 0 {t0 + t_rf}n 1.8 "
                f"{t0 + pw_ns}n 1.8 {t0 + pw_ns + t_rf}n 0)"
            )
    lines.append("")

    # WWL sources (held low -- no writing during compute)
    for r in range(n_rows):
        lines.append(f"Vwwl{r} wwl{r} 0 0")
    lines.append("")

    # Bitcell array instantiation
    lines.append(f"* {n_rows}x{n_cols} bitcell array")
    for r in range(n_rows):
        for c in range(n_cols):
            lines.append(
                f"Xcell_r{r}_c{c} bl{c} blb{c} wl{r} wwl{r} "
                f"q_r{r}c{c} qb_r{r}c{c} vdd vss cim_bitcell"
            )
    lines.append("")

    # Weight programming via initial conditions
    lines.append("* Weight programming (initial conditions)")
    for r in range(n_rows):
        for c in range(n_cols):
            w = weight_matrix[r, c]
            q_val = VDD if w == 1 else 0
            qb_val = 0 if w == 1 else VDD
            lines.append(f".ic v(q_r{r}c{c})={q_val} v(qb_r{r}c{c})={qb_val}")
    lines.append("")

    # Simulation control
    lines.append(f".tran 0.1n {t_sim_ns}n UIC")
    lines.append("")

    # Measurements: bitline voltages after compute settles
    t_meas_ns = t_start_ns + t_max_pulse_ns + 15  # measure after settle
    for c in range(n_cols):
        lines.append(f".meas tran vbl{c} FIND v(bl{c}) AT={t_meas_ns}n")
    lines.append("")

    # Power measurement
    lines.append(f".meas tran avg_power AVG power FROM=0 TO={t_sim_ns}n")
    lines.append("")

    # Save signals
    save_sigs = " ".join([f"v(bl{c})" for c in range(n_cols)])
    save_sigs += " " + " ".join([f"v(wl{r})" for r in range(n_rows)])
    save_sigs += " v(pre)"
    lines.append(f".save {save_sigs}")
    lines.append("")

    lines.append(".control")
    lines.append("run")
    lines.append(".endc")
    lines.append("")
    lines.append(".end")

    return "\n".join(lines), t_meas_ns


# ---------------------------------------------------------------------------
# Simulation runner
# ---------------------------------------------------------------------------

def run_ngspice(netlist_text, work_dir=None):
    """Run ngspice on the given netlist and return stdout."""
    if work_dir is None:
        work_dir = str(BLOCK_DIR)

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".cir", dir=work_dir, delete=False
    ) as f:
        f.write(netlist_text)
        cir_path = f.name

    try:
        result = subprocess.run(
            ["ngspice", "-b", cir_path],
            capture_output=True, text=True, timeout=120,
            cwd=work_dir,
        )
        return result.stdout + result.stderr, result.returncode
    except subprocess.TimeoutExpired:
        return "TIMEOUT", -1
    finally:
        try:
            os.unlink(cir_path)
        except OSError:
            pass


def parse_measurements(output, n_cols):
    """Parse .meas results from ngspice output."""
    results = {}
    for c in range(n_cols):
        pattern = rf"vbl{c}\s*=\s*([0-9eE.+-]+)"
        m = re.search(pattern, output, re.IGNORECASE)
        if m:
            results[f"vbl{c}"] = float(m.group(1))

    # Power
    m = re.search(r"avg_power\s*=\s*([0-9eE.+-]+)", output, re.IGNORECASE)
    if m:
        results["avg_power"] = float(m.group(1))

    return results


# ---------------------------------------------------------------------------
# MVM computation and comparison
# ---------------------------------------------------------------------------

def compute_ideal_mvm(weight_matrix, input_vector, t_lsb_ns, i_read_ua, c_bl_ff):
    """
    Compute ideal bitline voltages from the MVM.
    V_BL[j] = VDD - (1/C_BL) * sum_i( W[i][j] * I_READ * T_pulse[i] )
    """
    n_rows, n_cols = weight_matrix.shape
    pulse_widths_s = input_vector * t_lsb_ns * 1e-9  # convert to seconds
    i_read_a = i_read_ua * 1e-6
    c_bl_f = c_bl_ff * 1e-15

    # Dot product: W^T @ pulse_widths gives charge-per-column / I_read
    dot = weight_matrix.T @ pulse_widths_s  # shape (n_cols,)
    delta_v = (i_read_a * dot) / c_bl_f
    v_bl = VDD - delta_v

    # Clamp to [0, VDD]
    v_bl = np.clip(v_bl, 0, VDD)
    return v_bl


def compute_mvm_from_voltages(v_bl_sim, v_bl_ideal):
    """
    Compute RMSE and max error between simulated and ideal MVM results.
    Errors are normalised to the full-scale range.
    """
    # Full scale = maximum possible voltage drop
    v_range = VDD  # full scale is VDD (from VDD to 0)

    errors = np.abs(v_bl_sim - v_bl_ideal)
    rmse = np.sqrt(np.mean(errors ** 2)) / v_range * 100  # percent
    max_err = np.max(errors) / v_range * 100  # percent

    return rmse, max_err


# ---------------------------------------------------------------------------
# Main evaluation
# ---------------------------------------------------------------------------

def evaluate(params=None, n_rows=8, n_cols=8, n_tests=N_TEST_VECTORS,
             verbose=True, seed=42):
    """
    Run the full MVM evaluation.
    Returns dict with mvm_rmse_pct, max_error_pct, compute_time_ns, power_mw.
    """
    if params is None:
        params = load_parameters()

    bitcell_params = load_bitcell_params()
    pwm_params = load_pwm_params()

    np.random.seed(seed)

    all_rmse = []
    all_max_err = []
    all_power = []

    for t in range(n_tests):
        # Random binary weight matrix
        W = np.random.randint(0, 2, size=(n_rows, n_cols))
        # Random 4-bit input vector
        x = np.random.randint(0, 2**INPUT_BITS, size=(n_rows,))

        if verbose:
            print(f"\n--- Test vector {t+1}/{n_tests} ---")
            print(f"Input vector: {x}")
            print(f"Weight matrix sum per column: {W.sum(axis=0)}")

        # Generate and run simulation
        netlist, t_meas = generate_netlist(
            n_rows, n_cols, W, x, params, bitcell_params, pwm_params
        )
        output, rc = run_ngspice(netlist)

        if rc != 0 and "error" in output.lower():
            print(f"WARNING: ngspice returned errors for test {t+1}")
            if verbose:
                # Print last 20 lines for debugging
                for line in output.split("\n")[-20:]:
                    print(f"  {line}")
            continue

        # Parse results
        meas = parse_measurements(output, n_cols)

        if len(meas) < n_cols:
            print(f"WARNING: Only got {len(meas)} measurements, expected {n_cols}")
            continue

        # Extract simulated bitline voltages
        v_bl_sim = np.array([meas.get(f"vbl{c}", VDD) for c in range(n_cols)])

        # Compute ideal result
        c_bl_total_ff = n_rows * bitcell_params["c_bl_cell_ff"] + params["Cbl_extra_ff"]
        v_bl_ideal = compute_ideal_mvm(
            W, x, pwm_params["t_lsb_ns"],
            bitcell_params["i_read_ua"], c_bl_total_ff
        )

        # Compare
        rmse, max_err = compute_mvm_from_voltages(v_bl_sim, v_bl_ideal)
        all_rmse.append(rmse)
        all_max_err.append(max_err)

        if "avg_power" in meas:
            power_mw = abs(meas["avg_power"]) * 1e3
            all_power.append(power_mw)

        if verbose:
            print(f"Simulated BL voltages: {v_bl_sim}")
            print(f"Ideal BL voltages:     {v_bl_ideal}")
            print(f"RMSE: {rmse:.2f}%  Max error: {max_err:.2f}%")

    if not all_rmse:
        print("ERROR: No successful simulations")
        return None

    # Compute time: from precharge end to measurement point
    compute_time_ns = t_meas - params["Tpre_ns"]

    results = {
        "mvm_rmse_pct": float(np.mean(all_rmse)),
        "max_error_pct": float(np.max(all_max_err)),
        "compute_time_ns": float(compute_time_ns),
        "power_mw": float(np.mean(all_power)) if all_power else 0.0,
        "n_tests": len(all_rmse),
        "array_size": f"{n_rows}x{n_cols}",
    }

    if verbose:
        print(f"\n{'='*60}")
        print(f"ARRAY EVALUATION RESULTS ({n_rows}x{n_cols})")
        print(f"{'='*60}")
        for k, v in results.items():
            print(f"  {k}: {v}")

    return results


# ---------------------------------------------------------------------------
# Scoring / cost function
# ---------------------------------------------------------------------------

def score(results, specs=None):
    """
    Compute a weighted cost from the evaluation results.
    Lower is better. 0 = all specs met with margin.
    """
    if results is None:
        return 1e6

    if specs is None:
        specs = load_specs()

    measurements = specs["measurements"]
    total_cost = 0.0

    for meas_name, spec in measurements.items():
        target_str = spec["target"]
        weight = spec["weight"]
        value = results.get(meas_name)

        if value is None:
            total_cost += weight * 100  # heavy penalty for missing
            continue

        # Parse target
        if target_str.startswith("<"):
            limit = float(target_str[1:])
            if value <= limit:
                # Met spec -- reward margin
                margin = (limit - value) / limit
                total_cost += weight * max(0, -margin)  # negative = bonus
            else:
                # Failed spec -- penalise
                overshoot = (value - limit) / limit
                total_cost += weight * (1 + overshoot * 10)
        elif target_str.startswith(">"):
            limit = float(target_str[1:])
            if value >= limit:
                margin = (value - limit) / limit
                total_cost += weight * max(0, -margin)
            else:
                undershoot = (limit - value) / limit
                total_cost += weight * (1 + undershoot * 10)

    return total_cost


def passes_specs(results, specs=None):
    """Check if all specs are met."""
    if results is None:
        return False
    if specs is None:
        specs = load_specs()

    for meas_name, spec in specs["measurements"].items():
        target_str = spec["target"]
        value = results.get(meas_name)
        if value is None:
            return False
        if target_str.startswith("<"):
            if value >= float(target_str[1:]):
                return False
        elif target_str.startswith(">"):
            if value <= float(target_str[1:]):
                return False
    return True


# ---------------------------------------------------------------------------
# Save results
# ---------------------------------------------------------------------------

def save_results(results, filename="results.tsv"):
    """Append results to TSV file."""
    filepath = BLOCK_DIR / filename
    write_header = not filepath.exists()

    with open(filepath, "a") as f:
        if write_header:
            f.write("\t".join(results.keys()) + "\n")
        f.write("\t".join(str(v) for v in results.values()) + "\n")


def save_measurements(results, filename="measurements.json"):
    """Save measurements for downstream blocks."""
    filepath = BLOCK_DIR / filename
    with open(filepath, "w") as f:
        json.dump(results, f, indent=2)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("CIM Array Evaluation")
    print("=" * 60)

    # Start with 8x8 for fast iteration
    results = evaluate(n_rows=8, n_cols=8, n_tests=5, verbose=True)

    if results:
        cost = score(results)
        passed = passes_specs(results)
        print(f"\nCost: {cost:.2f}")
        print(f"Specs met: {passed}")

        save_results(results)
        save_measurements(results)
        print(f"\nResults saved to {BLOCK_DIR / 'results.tsv'}")
        print(f"Measurements saved to {BLOCK_DIR / 'measurements.json'}")
